language: objective-c

xcode_project: StyleKit.xcodeproj
xcode_scheme: StyleKit
osx_image: xcode9.1
xcode_sdk: macosx10.13

script:
  - xcodebuild clean build test -project StyleKit.xcodeproj -scheme StyleKit -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.1'
